import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"

INGREDIENTS = [

    # ─── SALT & PEPPER ───────────────────────────────────────────────
    ("Salt", "Salt", "Spices & Condiments"),
    ("Kosher Salt", "Salt", "Spices & Condiments"),
    ("Sea Salt", "Salt", "Spices & Condiments"),
    ("Table Salt", "Salt", "Spices & Condiments"),
    ("Flaky Sea Salt", "Salt", "Spices & Condiments"),
    ("Fleur De Sel", "Salt", "Spices & Condiments"),
    ("Pink Himalayan Salt", "Salt", "Spices & Condiments"),
    ("Black Pepper", "Black Pepper", "Spices & Condiments"),
    ("Ground Black Pepper", "Black Pepper", "Spices & Condiments"),
    ("Whole Black Peppercorns", "Black Pepper", "Spices & Condiments"),
    ("White Pepper", "White Pepper", "Spices & Condiments"),
    ("Ground White Pepper", "White Pepper", "Spices & Condiments"),
    ("Pink Peppercorns", "Pink Peppercorns", "Spices & Condiments"),
    ("Szechuan Peppercorns", "Szechuan Peppercorns", "Spices & Condiments"),

    # ─── DRIED HERBS ─────────────────────────────────────────────────
    ("Oregano", "Oregano", "Spices & Condiments"),
    ("Dried Oregano", "Oregano", "Spices & Condiments"),
    ("Thyme", "Thyme", "Spices & Condiments"),
    ("Dried Thyme", "Thyme", "Spices & Condiments"),
    ("Rosemary", "Rosemary", "Spices & Condiments"),
    ("Dried Rosemary", "Rosemary", "Spices & Condiments"),
    ("Basil", "Basil", "Spices & Condiments"),
    ("Dried Basil", "Basil", "Spices & Condiments"),
    ("Bay Leaves", "Bay Leaves", "Spices & Condiments"),
    ("Bay Leaf", "Bay Leaves", "Spices & Condiments"),
    ("Parsley", "Parsley", "Spices & Condiments"),
    ("Dried Parsley", "Parsley", "Spices & Condiments"),
    ("Sage", "Sage", "Spices & Condiments"),
    ("Dried Sage", "Sage", "Spices & Condiments"),
    ("Tarragon", "Tarragon", "Spices & Condiments"),
    ("Dried Tarragon", "Tarragon", "Spices & Condiments"),
    ("Marjoram", "Marjoram", "Spices & Condiments"),
    ("Dried Marjoram", "Marjoram", "Spices & Condiments"),
    ("Dill", "Dill", "Spices & Condiments"),
    ("Dried Dill", "Dill", "Spices & Condiments"),
    ("Chives", "Chives", "Spices & Condiments"),
    ("Dried Chives", "Chives", "Spices & Condiments"),
    ("Mint", "Mint", "Spices & Condiments"),
    ("Dried Mint", "Mint", "Spices & Condiments"),
    ("Herbes De Provence", "Herbes De Provence", "Spices & Condiments"),
    ("Italian Seasoning", "Italian Seasoning", "Spices & Condiments"),
    ("Bouquet Garni", "Bouquet Garni", "Spices & Condiments"),
    ("Dried Lavender", "Lavender", "Spices & Condiments"),
    ("Lemongrass", "Lemongrass", "Produce - Vegetables"),
    ("Dried Lemongrass", "Lemongrass", "Spices & Condiments"),
    ("Kaffir Lime Leaves", "Kaffir Lime Leaves", "Spices & Condiments"),
    ("Curry Leaves", "Curry Leaves", "Spices & Condiments"),

    # ─── SPICES ──────────────────────────────────────────────────────
    ("Garlic Powder", "Garlic Powder", "Spices & Condiments"),
    ("Onion Powder", "Onion Powder", "Spices & Condiments"),
    ("Cumin", "Cumin", "Spices & Condiments"),
    ("Ground Cumin", "Cumin", "Spices & Condiments"),
    ("Cumin Seeds", "Cumin Seeds", "Spices & Condiments"),
    ("Paprika", "Paprika", "Spices & Condiments"),
    ("Sweet Paprika", "Paprika", "Spices & Condiments"),
    ("Smoked Paprika", "Smoked Paprika", "Spices & Condiments"),
    ("Hot Paprika", "Hot Paprika", "Spices & Condiments"),
    ("Chili Powder", "Chili Powder", "Spices & Condiments"),
    ("Ancho Chili Powder", "Ancho Chili Powder", "Spices & Condiments"),
    ("Chipotle Powder", "Chipotle Powder", "Spices & Condiments"),
    ("Cayenne Pepper", "Cayenne Pepper", "Spices & Condiments"),
    ("Cayenne", "Cayenne Pepper", "Spices & Condiments"),
    ("Red Pepper Flakes", "Red Pepper Flakes", "Spices & Condiments"),
    ("Crushed Red Pepper", "Red Pepper Flakes", "Spices & Condiments"),
    ("Cinnamon", "Cinnamon", "Spices & Condiments"),
    ("Ground Cinnamon", "Cinnamon", "Spices & Condiments"),
    ("Cinnamon Sticks", "Cinnamon Sticks", "Spices & Condiments"),
    ("Nutmeg", "Nutmeg", "Spices & Condiments"),
    ("Ground Nutmeg", "Nutmeg", "Spices & Condiments"),
    ("Whole Nutmeg", "Nutmeg", "Spices & Condiments"),
    ("Allspice", "Allspice", "Spices & Condiments"),
    ("Ground Allspice", "Allspice", "Spices & Condiments"),
    ("Allspice Berries", "Allspice", "Spices & Condiments"),
    ("Cloves", "Cloves", "Spices & Condiments"),
    ("Ground Cloves", "Cloves", "Spices & Condiments"),
    ("Whole Cloves", "Cloves", "Spices & Condiments"),
    ("Cardamom", "Cardamom", "Spices & Condiments"),
    ("Ground Cardamom", "Cardamom", "Spices & Condiments"),
    ("Cardamom Pods", "Cardamom", "Spices & Condiments"),
    ("Turmeric", "Turmeric", "Spices & Condiments"),
    ("Ground Turmeric", "Turmeric", "Spices & Condiments"),
    ("Ginger", "Ginger", "Produce - Vegetables"),
    ("Fresh Ginger", "Ginger", "Produce - Vegetables"),
    ("Ground Ginger", "Ground Ginger", "Spices & Condiments"),
    ("Coriander", "Coriander", "Spices & Condiments"),
    ("Ground Coriander", "Coriander", "Spices & Condiments"),
    ("Coriander Seeds", "Coriander Seeds", "Spices & Condiments"),
    ("Fennel Seeds", "Fennel Seeds", "Spices & Condiments"),
    ("Mustard Seeds", "Mustard Seeds", "Spices & Condiments"),
    ("Yellow Mustard Seeds", "Mustard Seeds", "Spices & Condiments"),
    ("Black Mustard Seeds", "Mustard Seeds", "Spices & Condiments"),
    ("Celery Seeds", "Celery Seeds", "Spices & Condiments"),
    ("Celery Salt", "Celery Salt", "Spices & Condiments"),
    ("Caraway Seeds", "Caraway Seeds", "Spices & Condiments"),
    ("Poppy Seeds", "Poppy Seeds", "Spices & Condiments"),
    ("Sesame Seeds", "Sesame Seeds", "Spices & Condiments"),
    ("Black Sesame Seeds", "Sesame Seeds", "Spices & Condiments"),
    ("Toasted Sesame Seeds", "Sesame Seeds", "Spices & Condiments"),
    ("Nigella Seeds", "Nigella Seeds", "Spices & Condiments"),
    ("Fenugreek", "Fenugreek", "Spices & Condiments"),
    ("Fenugreek Seeds", "Fenugreek", "Spices & Condiments"),
    ("Star Anise", "Star Anise", "Spices & Condiments"),
    ("Anise Seeds", "Anise", "Spices & Condiments"),
    ("Sumac", "Sumac", "Spices & Condiments"),
    ("Za'Atar", "Za'Atar", "Spices & Condiments"),
    ("Harissa", "Harissa", "Spices & Condiments"),
    ("Ras El Hanout", "Ras El Hanout", "Spices & Condiments"),
    ("Garam Masala", "Garam Masala", "Spices & Condiments"),
    ("Curry Powder", "Curry Powder", "Spices & Condiments"),
    ("Madras Curry Powder", "Curry Powder", "Spices & Condiments"),
    ("Tandoori Masala", "Tandoori Masala", "Spices & Condiments"),
    ("Chinese Five Spice", "Chinese Five Spice", "Spices & Condiments"),
    ("Five Spice Powder", "Chinese Five Spice", "Spices & Condiments"),
    ("Old Bay Seasoning", "Old Bay Seasoning", "Spices & Condiments"),
    ("Cajun Seasoning", "Cajun Seasoning", "Spices & Condiments"),
    ("Creole Seasoning", "Creole Seasoning", "Spices & Condiments"),
    ("Taco Seasoning", "Taco Seasoning", "Spices & Condiments"),
    ("Chili Seasoning", "Chili Seasoning", "Spices & Condiments"),
    ("Steak Seasoning", "Steak Seasoning", "Spices & Condiments"),
    ("Montreal Steak Seasoning", "Steak Seasoning", "Spices & Condiments"),
    ("Everything Bagel Seasoning", "Everything Bagel Seasoning", "Spices & Condiments"),
    ("Lemon Pepper", "Lemon Pepper", "Spices & Condiments"),
    ("Onion Salt", "Onion Salt", "Spices & Condiments"),
    ("Garlic Salt", "Garlic Salt", "Spices & Condiments"),
    ("Seasoned Salt", "Seasoned Salt", "Spices & Condiments"),
    ("Adobo Seasoning", "Adobo Seasoning", "Spices & Condiments"),
    ("Sazon Seasoning", "Sazon Seasoning", "Spices & Condiments"),
    ("Furikake", "Furikake", "Spices & Condiments"),
    ("Dashi Powder", "Dashi Powder", "Spices & Condiments"),
    ("Miso Paste", "Miso Paste", "Spices & Condiments"),
    ("White Miso Paste", "Miso Paste", "Spices & Condiments"),
    ("Red Miso Paste", "Miso Paste", "Spices & Condiments"),
    ("Saffron", "Saffron", "Spices & Condiments"),

    # ─── OILS ────────────────────────────────────────────────────────
    ("Olive Oil", "Olive Oil", "Spices & Condiments"),
    ("Extra Virgin Olive Oil", "Olive Oil", "Spices & Condiments"),
    ("Light Olive Oil", "Olive Oil", "Spices & Condiments"),
    ("Vegetable Oil", "Vegetable Oil", "Spices & Condiments"),
    ("Canola Oil", "Canola Oil", "Spices & Condiments"),
    ("Sunflower Oil", "Sunflower Oil", "Spices & Condiments"),
    ("Safflower Oil", "Safflower Oil", "Spices & Condiments"),
    ("Corn Oil", "Corn Oil", "Spices & Condiments"),
    ("Peanut Oil", "Peanut Oil", "Spices & Condiments"),
    ("Sesame Oil", "Sesame Oil", "Spices & Condiments"),
    ("Toasted Sesame Oil", "Sesame Oil", "Spices & Condiments"),
    ("Coconut Oil", "Coconut Oil", "Spices & Condiments"),
    ("Avocado Oil", "Avocado Oil", "Spices & Condiments"),
    ("Grapeseed Oil", "Grapeseed Oil", "Spices & Condiments"),
    ("Walnut Oil", "Walnut Oil", "Spices & Condiments"),
    ("Truffle Oil", "Truffle Oil", "Spices & Condiments"),
    ("Chili Oil", "Chili Oil", "Spices & Condiments"),
    ("Nonstick Cooking Spray", "Cooking Spray", "Spices & Condiments"),
    ("Cooking Spray", "Cooking Spray", "Spices & Condiments"),

    # ─── VINEGARS ────────────────────────────────────────────────────
    ("White Vinegar", "White Vinegar", "Spices & Condiments"),
    ("Distilled White Vinegar", "White Vinegar", "Spices & Condiments"),
    ("Apple Cider Vinegar", "Apple Cider Vinegar", "Spices & Condiments"),
    ("Red Wine Vinegar", "Red Wine Vinegar", "Spices & Condiments"),
    ("White Wine Vinegar", "White Wine Vinegar", "Spices & Condiments"),
    ("Balsamic Vinegar", "Balsamic Vinegar", "Spices & Condiments"),
    ("Balsamic Glaze", "Balsamic Glaze", "Spices & Condiments"),
    ("Rice Vinegar", "Rice Vinegar", "Spices & Condiments"),
    ("Rice Wine Vinegar", "Rice Vinegar", "Spices & Condiments"),
    ("Sherry Vinegar", "Sherry Vinegar", "Spices & Condiments"),
    ("Champagne Vinegar", "Champagne Vinegar", "Spices & Condiments"),
    ("Malt Vinegar", "Malt Vinegar", "Spices & Condiments"),

    # ─── SAUCES & CONDIMENTS ─────────────────────────────────────────
    ("Soy Sauce", "Soy Sauce", "Spices & Condiments"),
    ("Low Sodium Soy Sauce", "Soy Sauce", "Spices & Condiments"),
    ("Tamari", "Tamari", "Spices & Condiments"),
    ("Coconut Aminos", "Coconut Aminos", "Spices & Condiments"),
    ("Fish Sauce", "Fish Sauce", "Spices & Condiments"),
    ("Oyster Sauce", "Oyster Sauce", "Spices & Condiments"),
    ("Hoisin Sauce", "Hoisin Sauce", "Spices & Condiments"),
    ("Worcestershire Sauce", "Worcestershire Sauce", "Spices & Condiments"),
    ("Hot Sauce", "Hot Sauce", "Spices & Condiments"),
    ("Tabasco", "Hot Sauce", "Spices & Condiments"),
    ("Sriracha", "Sriracha", "Spices & Condiments"),
    ("Sambal Oelek", "Sambal Oelek", "Spices & Condiments"),
    ("Gochujang", "Gochujang", "Spices & Condiments"),
    ("Gochugaru", "Gochugaru", "Spices & Condiments"),
    ("Chili Garlic Sauce", "Chili Garlic Sauce", "Spices & Condiments"),
    ("Sweet Chili Sauce", "Sweet Chili Sauce", "Spices & Condiments"),
    ("Teriyaki Sauce", "Teriyaki Sauce", "Spices & Condiments"),
    ("Ponzu Sauce", "Ponzu Sauce", "Spices & Condiments"),
    ("Dijon Mustard", "Dijon Mustard", "Spices & Condiments"),
    ("Whole Grain Mustard", "Whole Grain Mustard", "Spices & Condiments"),
    ("Yellow Mustard", "Mustard", "Spices & Condiments"),
    ("Spicy Brown Mustard", "Mustard", "Spices & Condiments"),
    ("Honey Mustard", "Honey Mustard", "Spices & Condiments"),
    ("Ketchup", "Ketchup", "Spices & Condiments"),
    ("Mayonnaise", "Mayonnaise", "Spices & Condiments"),
    ("Aioli", "Aioli", "Spices & Condiments"),
    ("Tahini", "Tahini", "Spices & Condiments"),
    ("Harissa Paste", "Harissa", "Spices & Condiments"),
    ("Tomato Paste", "Tomato Paste", "Pantry & Dry Goods"),
    ("Tomato Sauce", "Tomato Sauce", "Pantry & Dry Goods"),
    ("Marinara Sauce", "Marinara Sauce", "Pantry & Dry Goods"),
    ("Passata", "Passata", "Pantry & Dry Goods"),
    ("Barbecue Sauce", "Barbecue Sauce", "Spices & Condiments"),
    ("BBQ Sauce", "Barbecue Sauce", "Spices & Condiments"),
    ("Pesto", "Pesto", "Spices & Condiments"),
    ("Basil Pesto", "Pesto", "Spices & Condiments"),
    ("Sun-Dried Tomato Pesto", "Pesto", "Spices & Condiments"),
    ("Tzatziki", "Tzatziki", "Dairy & Eggs"),
    ("Hummus", "Hummus", "Pantry & Dry Goods"),
    ("Ranch Dressing", "Ranch Dressing", "Spices & Condiments"),
    ("Caesar Dressing", "Caesar Dressing", "Spices & Condiments"),
    ("Italian Dressing", "Italian Dressing", "Spices & Condiments"),
    ("Balsamic Dressing", "Balsamic Dressing", "Spices & Condiments"),
    ("Vinaigrette", "Vinaigrette", "Spices & Condiments"),
    ("Mirin", "Mirin", "Spices & Condiments"),
    ("Sake", "Sake", "Pantry & Dry Goods"),
    ("Rice Wine", "Rice Wine", "Pantry & Dry Goods"),
    ("Shaoxing Wine", "Shaoxing Wine", "Pantry & Dry Goods"),

    # ─── SWEETENERS ──────────────────────────────────────────────────
    ("Granulated Sugar", "Sugar", "Pantry & Dry Goods"),
    ("White Sugar", "Sugar", "Pantry & Dry Goods"),
    ("Sugar", "Sugar", "Pantry & Dry Goods"),
    ("Brown Sugar", "Brown Sugar", "Pantry & Dry Goods"),
    ("Light Brown Sugar", "Brown Sugar", "Pantry & Dry Goods"),
    ("Dark Brown Sugar", "Brown Sugar", "Pantry & Dry Goods"),
    ("Powdered Sugar", "Powdered Sugar", "Pantry & Dry Goods"),
    ("Confectioners Sugar", "Powdered Sugar", "Pantry & Dry Goods"),
    ("Icing Sugar", "Powdered Sugar", "Pantry & Dry Goods"),
    ("Raw Sugar", "Raw Sugar", "Pantry & Dry Goods"),
    ("Turbinado Sugar", "Raw Sugar", "Pantry & Dry Goods"),
    ("Demerara Sugar", "Raw Sugar", "Pantry & Dry Goods"),
    ("Coconut Sugar", "Coconut Sugar", "Pantry & Dry Goods"),
    ("Honey", "Honey", "Pantry & Dry Goods"),
    ("Maple Syrup", "Maple Syrup", "Pantry & Dry Goods"),
    ("Pure Maple Syrup", "Maple Syrup", "Pantry & Dry Goods"),
    ("Agave Nectar", "Agave", "Pantry & Dry Goods"),
    ("Agave Syrup", "Agave", "Pantry & Dry Goods"),
    ("Molasses", "Molasses", "Pantry & Dry Goods"),
    ("Blackstrap Molasses", "Molasses", "Pantry & Dry Goods"),
    ("Corn Syrup", "Corn Syrup", "Pantry & Dry Goods"),
    ("Light Corn Syrup", "Corn Syrup", "Pantry & Dry Goods"),
    ("Dark Corn Syrup", "Corn Syrup", "Pantry & Dry Goods"),
    ("Simple Syrup", "Simple Syrup", "Pantry & Dry Goods"),
    ("Stevia", "Stevia", "Pantry & Dry Goods"),

    # ─── BAKING ──────────────────────────────────────────────────────
    ("All-Purpose Flour", "All-Purpose Flour", "Pantry & Dry Goods"),
    ("Bread Flour", "Bread Flour", "Pantry & Dry Goods"),
    ("Cake Flour", "Cake Flour", "Pantry & Dry Goods"),
    ("Pastry Flour", "Pastry Flour", "Pantry & Dry Goods"),
    ("Whole Wheat Flour", "Whole Wheat Flour", "Pantry & Dry Goods"),
    ("White Whole Wheat Flour", "Whole Wheat Flour", "Pantry & Dry Goods"),
    ("Bread Machine Flour", "Bread Flour", "Pantry & Dry Goods"),
    ("Rye Flour", "Rye Flour", "Pantry & Dry Goods"),
    ("Almond Flour", "Almond Flour", "Pantry & Dry Goods"),
    ("Almond Meal", "Almond Flour", "Pantry & Dry Goods"),
    ("Coconut Flour", "Coconut Flour", "Pantry & Dry Goods"),
    ("Oat Flour", "Oat Flour", "Pantry & Dry Goods"),
    ("Rice Flour", "Rice Flour", "Pantry & Dry Goods"),
    ("Chickpea Flour", "Chickpea Flour", "Pantry & Dry Goods"),
    ("Semolina Flour", "Semolina", "Pantry & Dry Goods"),
    ("Semolina", "Semolina", "Pantry & Dry Goods"),
    ("Cornmeal", "Cornmeal", "Pantry & Dry Goods"),
    ("Polenta", "Polenta", "Pantry & Dry Goods"),
    ("Cornstarch", "Cornstarch", "Pantry & Dry Goods"),
    ("Arrowroot Powder", "Arrowroot", "Pantry & Dry Goods"),
    ("Arrowroot Starch", "Arrowroot", "Pantry & Dry Goods"),
    ("Tapioca Starch", "Tapioca Starch", "Pantry & Dry Goods"),
    ("Tapioca Flour", "Tapioca Starch", "Pantry & Dry Goods"),
    ("Baking Soda", "Baking Soda", "Pantry & Dry Goods"),
    ("Baking Powder", "Baking Powder", "Pantry & Dry Goods"),
    ("Cream Of Tartar", "Cream Of Tartar", "Pantry & Dry Goods"),
    ("Active Dry Yeast", "Yeast", "Pantry & Dry Goods"),
    ("Instant Yeast", "Yeast", "Pantry & Dry Goods"),
    ("Rapid Rise Yeast", "Yeast", "Pantry & Dry Goods"),
    ("Fresh Yeast", "Yeast", "Pantry & Dry Goods"),
    ("Vanilla Extract", "Vanilla Extract", "Spices & Condiments"),
    ("Pure Vanilla Extract", "Vanilla Extract", "Spices & Condiments"),
    ("Vanilla Bean", "Vanilla Bean", "Spices & Condiments"),
    ("Vanilla Paste", "Vanilla Paste", "Spices & Condiments"),
    ("Almond Extract", "Almond Extract", "Spices & Condiments"),
    ("Peppermint Extract", "Peppermint Extract", "Spices & Condiments"),
    ("Lemon Extract", "Lemon Extract", "Spices & Condiments"),
    ("Orange Extract", "Orange Extract", "Spices & Condiments"),
    ("Cocoa Powder", "Cocoa Powder", "Pantry & Dry Goods"),
    ("Unsweetened Cocoa Powder", "Cocoa Powder", "Pantry & Dry Goods"),
    ("Dutch Process Cocoa Powder", "Cocoa Powder", "Pantry & Dry Goods"),
    ("Cacao Powder", "Cocoa Powder", "Pantry & Dry Goods"),
    ("Chocolate Chips", "Chocolate Chips", "Pantry & Dry Goods"),
    ("Semi-Sweet Chocolate Chips", "Chocolate Chips", "Pantry & Dry Goods"),
    ("Dark Chocolate Chips", "Chocolate Chips", "Pantry & Dry Goods"),
    ("White Chocolate Chips", "White Chocolate Chips", "Pantry & Dry Goods"),
    ("Dark Chocolate", "Dark Chocolate", "Pantry & Dry Goods"),
    ("Semi-Sweet Chocolate", "Dark Chocolate", "Pantry & Dry Goods"),
    ("Bittersweet Chocolate", "Dark Chocolate", "Pantry & Dry Goods"),
    ("Milk Chocolate", "Milk Chocolate", "Pantry & Dry Goods"),
    ("White Chocolate", "White Chocolate", "Pantry & Dry Goods"),
    ("Unsweetened Chocolate", "Unsweetened Chocolate", "Pantry & Dry Goods"),
    ("Cocoa Nibs", "Cocoa Nibs", "Pantry & Dry Goods"),
    ("Chocolate Bar", "Chocolate Bar", "Pantry & Dry Goods"),
    ("Sprinkles", "Sprinkles", "Pantry & Dry Goods"),
    ("Food Coloring", "Food Coloring", "Pantry & Dry Goods"),
    ("Gelatin", "Gelatin", "Pantry & Dry Goods"),
    ("Unflavored Gelatin", "Gelatin", "Pantry & Dry Goods"),
    ("Pectin", "Pectin", "Pantry & Dry Goods"),
    ("Agar Agar", "Agar Agar", "Pantry & Dry Goods"),
    ("Breadcrumbs", "Breadcrumbs", "Pantry & Dry Goods"),
    ("Panko Breadcrumbs", "Breadcrumbs", "Pantry & Dry Goods"),
    ("Italian Breadcrumbs", "Breadcrumbs", "Pantry & Dry Goods"),

    # ─── DAIRY & EGGS ────────────────────────────────────────────────
    ("Butter", "Butter", "Dairy & Eggs"),
    ("Unsalted Butter", "Butter", "Dairy & Eggs"),
    ("Salted Butter", "Butter", "Dairy & Eggs"),
    ("European Butter", "Butter", "Dairy & Eggs"),
    ("Clarified Butter", "Clarified Butter", "Dairy & Eggs"),
    ("Ghee", "Ghee", "Dairy & Eggs"),
    ("Brown Butter", "Brown Butter", "Dairy & Eggs"),
    ("Vegan Butter", "Vegan Butter", "Dairy & Eggs"),
    ("Whole Milk", "Milk", "Dairy & Eggs"),
    ("2% Milk", "Milk", "Dairy & Eggs"),
    ("1% Milk", "Milk", "Dairy & Eggs"),
    ("Skim Milk", "Milk", "Dairy & Eggs"),
    ("Milk", "Milk", "Dairy & Eggs"),
    ("Buttermilk", "Buttermilk", "Dairy & Eggs"),
    ("Evaporated Milk", "Evaporated Milk", "Pantry & Dry Goods"),
    ("Sweetened Condensed Milk", "Sweetened Condensed Milk", "Pantry & Dry Goods"),
    ("Powdered Milk", "Powdered Milk", "Pantry & Dry Goods"),
    ("Dry Milk Powder", "Powdered Milk", "Pantry & Dry Goods"),
    ("Oat Milk", "Oat Milk", "Dairy & Eggs"),
    ("Almond Milk", "Almond Milk", "Dairy & Eggs"),
    ("Soy Milk", "Soy Milk", "Dairy & Eggs"),
    ("Coconut Milk Beverage", "Coconut Milk Beverage", "Dairy & Eggs"),
    ("Heavy Cream", "Heavy Cream", "Dairy & Eggs"),
    ("Heavy Whipping Cream", "Heavy Cream", "Dairy & Eggs"),
    ("Whipping Cream", "Heavy Cream", "Dairy & Eggs"),
    ("Light Cream", "Light Cream", "Dairy & Eggs"),
    ("Half And Half", "Half And Half", "Dairy & Eggs"),
    ("Sour Cream", "Sour Cream", "Dairy & Eggs"),
    ("Creme Fraiche", "Creme Fraiche", "Dairy & Eggs"),
    ("Greek Yogurt", "Greek Yogurt", "Dairy & Eggs"),
    ("Plain Yogurt", "Yogurt", "Dairy & Eggs"),
    ("Whole Milk Yogurt", "Yogurt", "Dairy & Eggs"),
    ("Yogurt", "Yogurt", "Dairy & Eggs"),
    ("Labneh", "Labneh", "Dairy & Eggs"),
    ("Cream Cheese", "Cream Cheese", "Dairy & Eggs"),
    ("Neufchatel Cheese", "Cream Cheese", "Dairy & Eggs"),
    ("Mascarpone", "Mascarpone", "Dairy & Eggs"),
    ("Ricotta Cheese", "Ricotta", "Dairy & Eggs"),
    ("Ricotta", "Ricotta", "Dairy & Eggs"),
    ("Cottage Cheese", "Cottage Cheese", "Dairy & Eggs"),
    ("Parmesan Cheese", "Parmesan", "Dairy & Eggs"),
    ("Parmigiano Reggiano", "Parmesan", "Dairy & Eggs"),
    ("Pecorino Romano", "Pecorino Romano", "Dairy & Eggs"),
    ("Grana Padano", "Parmesan", "Dairy & Eggs"),
    ("Mozzarella Cheese", "Mozzarella", "Dairy & Eggs"),
    ("Fresh Mozzarella", "Mozzarella", "Dairy & Eggs"),
    ("Buffalo Mozzarella", "Mozzarella", "Dairy & Eggs"),
    ("Cheddar Cheese", "Cheddar", "Dairy & Eggs"),
    ("Sharp Cheddar", "Cheddar", "Dairy & Eggs"),
    ("Mild Cheddar", "Cheddar", "Dairy & Eggs"),
    ("White Cheddar", "Cheddar", "Dairy & Eggs"),
    ("Gruyere Cheese", "Gruyere", "Dairy & Eggs"),
    ("Swiss Cheese", "Swiss Cheese", "Dairy & Eggs"),
    ("Emmental Cheese", "Swiss Cheese", "Dairy & Eggs"),
    ("Gouda Cheese", "Gouda", "Dairy & Eggs"),
    ("Smoked Gouda", "Gouda", "Dairy & Eggs"),
    ("Aged Gouda", "Gouda", "Dairy & Eggs"),
    ("Brie Cheese", "Brie", "Dairy & Eggs"),
    ("Camembert Cheese", "Camembert", "Dairy & Eggs"),
    ("Feta Cheese", "Feta", "Dairy & Eggs"),
    ("Feta", "Feta", "Dairy & Eggs"),
    ("Goat Cheese", "Goat Cheese", "Dairy & Eggs"),
    ("Chevre", "Goat Cheese", "Dairy & Eggs"),
    ("Blue Cheese", "Blue Cheese", "Dairy & Eggs"),
    ("Gorgonzola", "Blue Cheese", "Dairy & Eggs"),
    ("Roquefort", "Blue Cheese", "Dairy & Eggs"),
    ("Stilton", "Blue Cheese", "Dairy & Eggs"),
    ("Monterey Jack Cheese", "Monterey Jack", "Dairy & Eggs"),
    ("Pepper Jack Cheese", "Pepper Jack", "Dairy & Eggs"),
    ("Colby Jack Cheese", "Colby Jack", "Dairy & Eggs"),
    ("American Cheese", "American Cheese", "Dairy & Eggs"),
    ("Provolone Cheese", "Provolone", "Dairy & Eggs"),
    ("Fontina Cheese", "Fontina", "Dairy & Eggs"),
    ("Havarti Cheese", "Havarti", "Dairy & Eggs"),
    ("Manchego Cheese", "Manchego", "Dairy & Eggs"),
    ("Asiago Cheese", "Asiago", "Dairy & Eggs"),
    ("Burrata", "Burrata", "Dairy & Eggs"),
    ("Halloumi", "Halloumi", "Dairy & Eggs"),
    ("Paneer", "Paneer", "Dairy & Eggs"),
    ("Queso Fresco", "Queso Fresco", "Dairy & Eggs"),
    ("Cotija Cheese", "Cotija", "Dairy & Eggs"),
    ("Queso Blanco", "Queso Blanco", "Dairy & Eggs"),
    ("Shredded Cheese", "Shredded Cheese", "Dairy & Eggs"),
    ("Mexican Blend Cheese", "Shredded Cheese", "Dairy & Eggs"),
    ("Italian Blend Cheese", "Shredded Cheese", "Dairy & Eggs"),
    ("Eggs", "Eggs", "Dairy & Eggs"),
    ("Large Eggs", "Eggs", "Dairy & Eggs"),
    ("Extra Large Eggs", "Eggs", "Dairy & Eggs"),
    ("Medium Eggs", "Eggs", "Dairy & Eggs"),
    ("Egg Whites", "Egg Whites", "Dairy & Eggs"),
    ("Egg Yolks", "Egg Yolks", "Dairy & Eggs"),
    ("Duck Eggs", "Duck Eggs", "Dairy & Eggs"),
    ("Quail Eggs", "Quail Eggs", "Dairy & Eggs"),

    # ─── PRODUCE — VEGETABLES ────────────────────────────────────────
    ("Garlic", "Garlic", "Produce - Vegetables"),
    ("Garlic Cloves", "Garlic", "Produce - Vegetables"),
    ("Garlic Head", "Garlic", "Produce - Vegetables"),
    ("Whole Garlic", "Garlic", "Produce - Vegetables"),
    ("Black Garlic", "Black Garlic", "Produce - Vegetables"),
    ("Yellow Onion", "Onion", "Produce - Vegetables"),
    ("White Onion", "Onion", "Produce - Vegetables"),
    ("Sweet Onion", "Onion", "Produce - Vegetables"),
    ("Vidalia Onion", "Onion", "Produce - Vegetables"),
    ("Red Onion", "Red Onion", "Produce - Vegetables"),
    ("Onion", "Onion", "Produce - Vegetables"),
    ("Shallots", "Shallots", "Produce - Vegetables"),
    ("Shallot", "Shallots", "Produce - Vegetables"),
    ("Scallions", "Scallions", "Produce - Vegetables"),
    ("Green Onions", "Scallions", "Produce - Vegetables"),
    ("Spring Onions", "Scallions", "Produce - Vegetables"),
    ("Leeks", "Leeks", "Produce - Vegetables"),
    ("Leek", "Leeks", "Produce - Vegetables"),
    ("Chives", "Chives", "Produce - Vegetables"),
    ("Celery", "Celery", "Produce - Vegetables"),
    ("Celery Stalks", "Celery", "Produce - Vegetables"),
    ("Celery Root", "Celery Root", "Produce - Vegetables"),
    ("Celeriac", "Celery Root", "Produce - Vegetables"),
    ("Carrots", "Carrots", "Produce - Vegetables"),
    ("Baby Carrots", "Carrots", "Produce - Vegetables"),
    ("Rainbow Carrots", "Carrots", "Produce - Vegetables"),
    ("Parsnips", "Parsnips", "Produce - Vegetables"),
    ("Parsnip", "Parsnips", "Produce - Vegetables"),
    ("Turnips", "Turnips", "Produce - Vegetables"),
    ("Turnip", "Turnips", "Produce - Vegetables"),
    ("Rutabaga", "Rutabaga", "Produce - Vegetables"),
    ("Beets", "Beets", "Produce - Vegetables"),
    ("Red Beets", "Beets", "Produce - Vegetables"),
    ("Golden Beets", "Beets", "Produce - Vegetables"),
    ("Radishes", "Radishes", "Produce - Vegetables"),
    ("Daikon Radish", "Daikon", "Produce - Vegetables"),
    ("Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Russet Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Yukon Gold Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Red Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Fingerling Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Baby Potatoes", "Potatoes", "Produce - Vegetables"),
    ("New Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Purple Potatoes", "Potatoes", "Produce - Vegetables"),
    ("Sweet Potatoes", "Sweet Potatoes", "Produce - Vegetables"),
    ("Yams", "Sweet Potatoes", "Produce - Vegetables"),
    ("Garnet Yams", "Sweet Potatoes", "Produce - Vegetables"),
    ("Tomatoes", "Tomatoes", "Produce - Vegetables"),
    ("Roma Tomatoes", "Roma Tomatoes", "Produce - Vegetables"),
    ("Plum Tomatoes", "Roma Tomatoes", "Produce - Vegetables"),
    ("Cherry Tomatoes", "Cherry Tomatoes", "Produce - Vegetables"),
    ("Grape Tomatoes", "Cherry Tomatoes", "Produce - Vegetables"),
    ("Heirloom Tomatoes", "Heirloom Tomatoes", "Produce - Vegetables"),
    ("Beefsteak Tomatoes", "Tomatoes", "Produce - Vegetables"),
    ("Sun-Dried Tomatoes", "Sun-Dried Tomatoes", "Pantry & Dry Goods"),
    ("Bell Pepper", "Bell Pepper", "Produce - Vegetables"),
    ("Red Bell Pepper", "Red Bell Pepper", "Produce - Vegetables"),
    ("Green Bell Pepper", "Green Bell Pepper", "Produce - Vegetables"),
    ("Yellow Bell Pepper", "Yellow Bell Pepper", "Produce - Vegetables"),
    ("Orange Bell Pepper", "Orange Bell Pepper", "Produce - Vegetables"),
    ("Poblano Pepper", "Poblano", "Produce - Vegetables"),
    ("Anaheim Pepper", "Anaheim Pepper", "Produce - Vegetables"),
    ("Jalapeno", "Jalapeno", "Produce - Vegetables"),
    ("Jalapeno Pepper", "Jalapeno", "Produce - Vegetables"),
    ("Serrano Pepper", "Serrano", "Produce - Vegetables"),
    ("Habanero Pepper", "Habanero", "Produce - Vegetables"),
    ("Thai Chili", "Thai Chili", "Produce - Vegetables"),
    ("Bird's Eye Chili", "Thai Chili", "Produce - Vegetables"),
    ("Fresno Chili", "Fresno Chili", "Produce - Vegetables"),
    ("Dried Ancho Chili", "Ancho Chili", "Spices & Condiments"),
    ("Dried Guajillo Chili", "Guajillo Chili", "Spices & Condiments"),
    ("Dried Pasilla Chili", "Pasilla Chili", "Spices & Condiments"),
    ("Chipotle In Adobo", "Chipotle In Adobo", "Pantry & Dry Goods"),
    ("Zucchini", "Zucchini", "Produce - Vegetables"),
    ("Yellow Squash", "Yellow Squash", "Produce - Vegetables"),
    ("Butternut Squash", "Butternut Squash", "Produce - Vegetables"),
    ("Acorn Squash", "Acorn Squash", "Produce - Vegetables"),
    ("Delicata Squash", "Delicata Squash", "Produce - Vegetables"),
    ("Spaghetti Squash", "Spaghetti Squash", "Produce - Vegetables"),
    ("Pumpkin", "Pumpkin", "Produce - Vegetables"),
    ("Sugar Pumpkin", "Pumpkin", "Produce - Vegetables"),
    ("Eggplant", "Eggplant", "Produce - Vegetables"),
    ("Japanese Eggplant", "Eggplant", "Produce - Vegetables"),
    ("Italian Eggplant", "Eggplant", "Produce - Vegetables"),
    ("Cucumber", "Cucumber", "Produce - Vegetables"),
    ("English Cucumber", "Cucumber", "Produce - Vegetables"),
    ("Persian Cucumber", "Cucumber", "Produce - Vegetables"),
    ("Kirby Cucumber", "Cucumber", "Produce - Vegetables"),
    ("Broccoli", "Broccoli", "Produce - Vegetables"),
    ("Broccoli Florets", "Broccoli", "Produce - Vegetables"),
    ("Broccolini", "Broccolini", "Produce - Vegetables"),
    ("Broccoli Rabe", "Broccoli Rabe", "Produce - Vegetables"),
    ("Rapini", "Broccoli Rabe", "Produce - Vegetables"),
    ("Cauliflower", "Cauliflower", "Produce - Vegetables"),
    ("Cauliflower Florets", "Cauliflower", "Produce - Vegetables"),
    ("Purple Cauliflower", "Cauliflower", "Produce - Vegetables"),
    ("Romanesco", "Romanesco", "Produce - Vegetables"),
    ("Brussels Sprouts", "Brussels Sprouts", "Produce - Vegetables"),
    ("Cabbage", "Cabbage", "Produce - Vegetables"),
    ("Green Cabbage", "Cabbage", "Produce - Vegetables"),
    ("Red Cabbage", "Red Cabbage", "Produce - Vegetables"),
    ("Napa Cabbage", "Napa Cabbage", "Produce - Vegetables"),
    ("Savoy Cabbage", "Cabbage", "Produce - Vegetables"),
    ("Bok Choy", "Bok Choy", "Produce - Vegetables"),
    ("Baby Bok Choy", "Bok Choy", "Produce - Vegetables"),
    ("Spinach", "Spinach", "Produce - Vegetables"),
    ("Baby Spinach", "Spinach", "Produce - Vegetables"),
    ("Kale", "Kale", "Produce - Vegetables"),
    ("Curly Kale", "Kale", "Produce - Vegetables"),
    ("Lacinato Kale", "Kale", "Produce - Vegetables"),
    ("Dinosaur Kale", "Kale", "Produce - Vegetables"),
    ("Swiss Chard", "Swiss Chard", "Produce - Vegetables"),
    ("Rainbow Chard", "Swiss Chard", "Produce - Vegetables"),
    ("Collard Greens", "Collard Greens", "Produce - Vegetables"),
    ("Mustard Greens", "Mustard Greens", "Produce - Vegetables"),
    ("Arugula", "Arugula", "Produce - Vegetables"),
    ("Rocket", "Arugula", "Produce - Vegetables"),
    ("Romaine Lettuce", "Romaine", "Produce - Vegetables"),
    ("Butter Lettuce", "Butter Lettuce", "Produce - Vegetables"),
    ("Iceberg Lettuce", "Iceberg Lettuce", "Produce - Vegetables"),
    ("Mixed Greens", "Mixed Greens", "Produce - Vegetables"),
    ("Mesclun", "Mixed Greens", "Produce - Vegetables"),
    ("Watercress", "Watercress", "Produce - Vegetables"),
    ("Endive", "Endive", "Produce - Vegetables"),
    ("Radicchio", "Radicchio", "Produce - Vegetables"),
    ("Fennel", "Fennel", "Produce - Vegetables"),
    ("Fennel Bulb", "Fennel", "Produce - Vegetables"),
    ("Mushrooms", "Mushrooms", "Produce - Vegetables"),
    ("Button Mushrooms", "Mushrooms", "Produce - Vegetables"),
    ("Cremini Mushrooms", "Mushrooms", "Produce - Vegetables"),
    ("Baby Bella Mushrooms", "Mushrooms", "Produce - Vegetables"),
    ("Portobello Mushrooms", "Portobello Mushrooms", "Produce - Vegetables"),
    ("Portobello Caps", "Portobello Mushrooms", "Produce - Vegetables"),
    ("Shiitake Mushrooms", "Shiitake Mushrooms", "Produce - Vegetables"),
    ("Oyster Mushrooms", "Oyster Mushrooms", "Produce - Vegetables"),
    ("Maitake Mushrooms", "Maitake Mushrooms", "Produce - Vegetables"),
    ("Chanterelle Mushrooms", "Chanterelles", "Produce - Vegetables"),
    ("Porcini Mushrooms", "Porcini Mushrooms", "Produce - Vegetables"),
    ("Dried Porcini Mushrooms", "Dried Porcini", "Pantry & Dry Goods"),
    ("Dried Shiitake Mushrooms", "Dried Shiitake", "Pantry & Dry Goods"),
    ("Morel Mushrooms", "Morel Mushrooms", "Produce - Vegetables"),
    ("Enoki Mushrooms", "Enoki Mushrooms", "Produce - Vegetables"),
    ("Truffle", "Truffle", "Produce - Vegetables"),
    ("Black Truffle", "Truffle", "Produce - Vegetables"),
    ("White Truffle", "Truffle", "Produce - Vegetables"),
    ("Corn", "Corn", "Produce - Vegetables"),
    ("Sweet Corn", "Corn", "Produce - Vegetables"),
    ("Corn On The Cob", "Corn", "Produce - Vegetables"),
    ("Green Beans", "Green Beans", "Produce - Vegetables"),
    ("Haricots Verts", "Green Beans", "Produce - Vegetables"),
    ("French Green Beans", "Green Beans", "Produce - Vegetables"),
    ("Wax Beans", "Wax Beans", "Produce - Vegetables"),
    ("Snap Peas", "Snap Peas", "Produce - Vegetables"),
    ("Sugar Snap Peas", "Snap Peas", "Produce - Vegetables"),
    ("Snow Peas", "Snow Peas", "Produce - Vegetables"),
    ("Peas", "Peas", "Produce - Vegetables"),
    ("English Peas", "Peas", "Produce - Vegetables"),
    ("Edamame", "Edamame", "Produce - Vegetables"),
    ("Asparagus", "Asparagus", "Produce - Vegetables"),
    ("Asparagus Spears", "Asparagus", "Produce - Vegetables"),
    ("Artichoke", "Artichoke", "Produce - Vegetables"),
    ("Artichoke Hearts", "Artichoke Hearts", "Pantry & Dry Goods"),
    ("Canned Artichoke Hearts", "Artichoke Hearts", "Pantry & Dry Goods"),
    ("Okra", "Okra", "Produce - Vegetables"),
    ("Jicama", "Jicama", "Produce - Vegetables"),
    ("Water Chestnuts", "Water Chestnuts", "Pantry & Dry Goods"),
    ("Bamboo Shoots", "Bamboo Shoots", "Pantry & Dry Goods"),
    ("Bean Sprouts", "Bean Sprouts", "Produce - Vegetables"),
    ("Mung Bean Sprouts", "Bean Sprouts", "Produce - Vegetables"),
    ("Microgreens", "Microgreens", "Produce - Vegetables"),
    ("Fresh Herbs", "Fresh Herbs", "Produce - Vegetables"),
    ("Fresh Basil", "Basil", "Produce - Vegetables"),
    ("Fresh Parsley", "Parsley", "Produce - Vegetables"),
    ("Fresh Cilantro", "Cilantro", "Produce - Vegetables"),
    ("Cilantro", "Cilantro", "Produce - Vegetables"),
    ("Fresh Dill", "Dill", "Produce - Vegetables"),
    ("Fresh Mint", "Mint", "Produce - Vegetables"),
    ("Fresh Thyme", "Thyme", "Produce - Vegetables"),
    ("Fresh Rosemary", "Rosemary", "Produce - Vegetables"),
    ("Fresh Oregano", "Oregano", "Produce - Vegetables"),
    ("Fresh Sage", "Sage", "Produce - Vegetables"),
    ("Fresh Tarragon", "Tarragon", "Produce - Vegetables"),
    ("Fresh Chives", "Chives", "Produce - Vegetables"),

    # ─── PRODUCE — FRUIT ─────────────────────────────────────────────
    ("Lemon", "Lemon", "Produce - Fruit"),
    ("Lemons", "Lemon", "Produce - Fruit"),
    ("Meyer Lemon", "Lemon", "Produce - Fruit"),
    ("Lime", "Lime", "Produce - Fruit"),
    ("Limes", "Lime", "Produce - Fruit"),
    ("Key Lime", "Lime", "Produce - Fruit"),
    ("Orange", "Orange", "Produce - Fruit"),
    ("Oranges", "Orange", "Produce - Fruit"),
    ("Navel Orange", "Orange", "Produce - Fruit"),
    ("Blood Orange", "Blood Orange", "Produce - Fruit"),
    ("Mandarin Orange", "Mandarin", "Produce - Fruit"),
    ("Clementines", "Clementines", "Produce - Fruit"),
    ("Tangerine", "Tangerine", "Produce - Fruit"),
    ("Grapefruit", "Grapefruit", "Produce - Fruit"),
    ("Pink Grapefruit", "Grapefruit", "Produce - Fruit"),
    ("Lemon Zest", "Lemon Zest", "Produce - Fruit"),
    ("Lime Zest", "Lime Zest", "Produce - Fruit"),
    ("Orange Zest", "Orange Zest", "Produce - Fruit"),
    ("Lemon Juice", "Lemon Juice", "Produce - Fruit"),
    ("Lime Juice", "Lime Juice", "Produce - Fruit"),
    ("Orange Juice", "Orange Juice", "Produce - Fruit"),
    ("Apple", "Apple", "Produce - Fruit"),
    ("Apples", "Apple", "Produce - Fruit"),
    ("Granny Smith Apple", "Apple", "Produce - Fruit"),
    ("Honeycrisp Apple", "Apple", "Produce - Fruit"),
    ("Fuji Apple", "Apple", "Produce - Fruit"),
    ("Gala Apple", "Apple", "Produce - Fruit"),
    ("Pear", "Pear", "Produce - Fruit"),
    ("Pears", "Pear", "Produce - Fruit"),
    ("Bartlett Pear", "Pear", "Produce - Fruit"),
    ("Bosc Pear", "Pear", "Produce - Fruit"),
    ("Banana", "Banana", "Produce - Fruit"),
    ("Bananas", "Banana", "Produce - Fruit"),
    ("Plantain", "Plantain", "Produce - Fruit"),
    ("Avocado", "Avocado", "Produce - Fruit"),
    ("Avocados", "Avocado", "Produce - Fruit"),
    ("Hass Avocado", "Avocado", "Produce - Fruit"),
    ("Strawberries", "Strawberries", "Produce - Fruit"),
    ("Blueberries", "Blueberries", "Produce - Fruit"),
    ("Raspberries", "Raspberries", "Produce - Fruit"),
    ("Blackberries", "Blackberries", "Produce - Fruit"),
    ("Cranberries", "Cranberries", "Produce - Fruit"),
    ("Dried Cranberries", "Dried Cranberries", "Pantry & Dry Goods"),
    ("Cherries", "Cherries", "Produce - Fruit"),
    ("Bing Cherries", "Cherries", "Produce - Fruit"),
    ("Sour Cherries", "Sour Cherries", "Produce - Fruit"),
    ("Mango", "Mango", "Produce - Fruit"),
    ("Ataulfo Mango", "Mango", "Produce - Fruit"),
    ("Pineapple", "Pineapple", "Produce - Fruit"),
    ("Papaya", "Papaya", "Produce - Fruit"),
    ("Guava", "Guava", "Produce - Fruit"),
    ("Passion Fruit", "Passion Fruit", "Produce - Fruit"),
    ("Kiwi", "Kiwi", "Produce - Fruit"),
    ("Dragon Fruit", "Dragon Fruit", "Produce - Fruit"),
    ("Lychee", "Lychee", "Produce - Fruit"),
    ("Pomegranate", "Pomegranate", "Produce - Fruit"),
    ("Pomegranate Seeds", "Pomegranate", "Produce - Fruit"),
    ("Figs", "Figs", "Produce - Fruit"),
    ("Dried Figs", "Dried Figs", "Pantry & Dry Goods"),
    ("Dates", "Dates", "Pantry & Dry Goods"),
    ("Medjool Dates", "Dates", "Pantry & Dry Goods"),
    ("Raisins", "Raisins", "Pantry & Dry Goods"),
    ("Golden Raisins", "Raisins", "Pantry & Dry Goods"),
    ("Grapes", "Grapes", "Produce - Fruit"),
    ("Red Grapes", "Grapes", "Produce - Fruit"),
    ("Green Grapes", "Grapes", "Produce - Fruit"),
    ("Peach", "Peach", "Produce - Fruit"),
    ("Peaches", "Peach", "Produce - Fruit"),
    ("Nectarine", "Nectarine", "Produce - Fruit"),
    ("Plum", "Plum", "Produce - Fruit"),
    ("Plums", "Plum", "Produce - Fruit"),
    ("Apricot", "Apricot", "Produce - Fruit"),
    ("Dried Apricots", "Dried Apricots", "Pantry & Dry Goods"),
    ("Watermelon", "Watermelon", "Produce - Fruit"),
    ("Cantaloupe", "Cantaloupe", "Produce - Fruit"),
    ("Honeydew", "Honeydew", "Produce - Fruit"),

    # ─── MEAT ────────────────────────────────────────────────────────
    ("Chicken Breast", "Chicken Breast", "Meat & Seafood"),
    ("Boneless Skinless Chicken Breast", "Chicken Breast", "Meat & Seafood"),
    ("Boneless Chicken Breast", "Chicken Breast", "Meat & Seafood"),
    ("Bone-In Chicken Breast", "Bone-In Chicken Breast", "Meat & Seafood"),
    ("Split Chicken Breast", "Bone-In Chicken Breast", "Meat & Seafood"),
    ("Chicken Thighs", "Chicken Thighs", "Meat & Seafood"),
    ("Boneless Skinless Chicken Thighs", "Chicken Thighs", "Meat & Seafood"),
    ("Bone-In Chicken Thighs", "Bone-In Chicken Thighs", "Meat & Seafood"),
    ("Skin-On Chicken Thighs", "Bone-In Chicken Thighs", "Meat & Seafood"),
    ("Chicken Drumsticks", "Chicken Drumsticks", "Meat & Seafood"),
    ("Chicken Legs", "Chicken Legs", "Meat & Seafood"),
    ("Chicken Leg Quarters", "Chicken Leg Quarters", "Meat & Seafood"),
    ("Chicken Wings", "Chicken Wings", "Meat & Seafood"),
    ("Chicken Wing Flats", "Chicken Wings", "Meat & Seafood"),
    ("Chicken Drumettes", "Chicken Wings", "Meat & Seafood"),
    ("Whole Chicken", "Whole Chicken", "Meat & Seafood"),
    ("Rotisserie Chicken", "Rotisserie Chicken", "Meat & Seafood"),
    ("Chicken Tenders", "Chicken Tenders", "Meat & Seafood"),
    ("Chicken Tenderloin", "Chicken Tenders", "Meat & Seafood"),
    ("Ground Chicken", "Ground Chicken", "Meat & Seafood"),
    ("Ground Turkey", "Ground Turkey", "Meat & Seafood"),
    ("Turkey Breast", "Turkey Breast", "Meat & Seafood"),
    ("Turkey Tenderloin", "Turkey Tenderloin", "Meat & Seafood"),
    ("Whole Turkey", "Whole Turkey", "Meat & Seafood"),
    ("Turkey Thighs", "Turkey Thighs", "Meat & Seafood"),
    ("Turkey Legs", "Turkey Legs", "Meat & Seafood"),
    ("Duck Breast", "Duck Breast", "Meat & Seafood"),
    ("Duck Legs", "Duck Legs", "Meat & Seafood"),
    ("Whole Duck", "Whole Duck", "Meat & Seafood"),
    ("Ground Beef", "Ground Beef", "Meat & Seafood"),
    ("Ground Beef 80/20", "Ground Beef", "Meat & Seafood"),
    ("Ground Beef 90/10", "Ground Beef", "Meat & Seafood"),
    ("Lean Ground Beef", "Ground Beef", "Meat & Seafood"),
    ("Ribeye Steak", "Ribeye", "Meat & Seafood"),
    ("Ribeye", "Ribeye", "Meat & Seafood"),
    ("New York Strip Steak", "NY Strip", "Meat & Seafood"),
    ("Strip Steak", "NY Strip", "Meat & Seafood"),
    ("Sirloin Steak", "Sirloin", "Meat & Seafood"),
    ("Top Sirloin", "Sirloin", "Meat & Seafood"),
    ("Flank Steak", "Flank Steak", "Meat & Seafood"),
    ("Skirt Steak", "Skirt Steak", "Meat & Seafood"),
    ("Hanger Steak", "Hanger Steak", "Meat & Seafood"),
    ("Flat Iron Steak", "Flat Iron Steak", "Meat & Seafood"),
    ("Filet Mignon", "Filet Mignon", "Meat & Seafood"),
    ("Beef Tenderloin", "Beef Tenderloin", "Meat & Seafood"),
    ("T-Bone Steak", "T-Bone Steak", "Meat & Seafood"),
    ("Porterhouse Steak", "Porterhouse", "Meat & Seafood"),
    ("Chuck Roast", "Chuck Roast", "Meat & Seafood"),
    ("Pot Roast", "Chuck Roast", "Meat & Seafood"),
    ("Beef Brisket", "Brisket", "Meat & Seafood"),
    ("Brisket", "Brisket", "Meat & Seafood"),
    ("Short Ribs", "Short Ribs", "Meat & Seafood"),
    ("Beef Short Ribs", "Short Ribs", "Meat & Seafood"),
    ("Back Ribs", "Back Ribs", "Meat & Seafood"),
    ("Prime Rib", "Prime Rib", "Meat & Seafood"),
    ("Standing Rib Roast", "Prime Rib", "Meat & Seafood"),
    ("Beef Stew Meat", "Beef Stew Meat", "Meat & Seafood"),
    ("Beef Shank", "Beef Shank", "Meat & Seafood"),
    ("Oxtail", "Oxtail", "Meat & Seafood"),
    ("Veal Chops", "Veal", "Meat & Seafood"),
    ("Veal Cutlets", "Veal", "Meat & Seafood"),
    ("Veal Scallopini", "Veal", "Meat & Seafood"),
    ("Ground Veal", "Veal", "Meat & Seafood"),
    ("Pork Chops", "Pork Chops", "Meat & Seafood"),
    ("Bone-In Pork Chops", "Pork Chops", "Meat & Seafood"),
    ("Thick-Cut Pork Chops", "Pork Chops", "Meat & Seafood"),
    ("Pork Tenderloin", "Pork Tenderloin", "Meat & Seafood"),
    ("Pork Loin", "Pork Loin", "Meat & Seafood"),
    ("Pork Shoulder", "Pork Shoulder", "Meat & Seafood"),
    ("Pork Butt", "Pork Shoulder", "Meat & Seafood"),
    ("Boston Butt", "Pork Shoulder", "Meat & Seafood"),
    ("Pork Ribs", "Pork Ribs", "Meat & Seafood"),
    ("Baby Back Ribs", "Baby Back Ribs", "Meat & Seafood"),
    ("Spare Ribs", "Spare Ribs", "Meat & Seafood"),
    ("St. Louis Style Ribs", "Spare Ribs", "Meat & Seafood"),
    ("Ham", "Ham", "Meat & Seafood"),
    ("Bone-In Ham", "Ham", "Meat & Seafood"),
    ("Smoked Ham", "Ham", "Meat & Seafood"),
    ("Ham Hock", "Ham Hock", "Meat & Seafood"),
    ("Pork Belly", "Pork Belly", "Meat & Seafood"),
    ("Bacon", "Bacon", "Meat & Seafood"),
    ("Thick-Cut Bacon", "Bacon", "Meat & Seafood"),
    ("Turkey Bacon", "Turkey Bacon", "Meat & Seafood"),
    ("Canadian Bacon", "Canadian Bacon", "Meat & Seafood"),
    ("Pancetta", "Pancetta", "Meat & Seafood"),
    ("Guanciale", "Guanciale", "Meat & Seafood"),
    ("Prosciutto", "Prosciutto", "Meat & Seafood"),
    ("Prosciutto Di Parma", "Prosciutto", "Meat & Seafood"),
    ("Serrano Ham", "Serrano Ham", "Meat & Seafood"),
    ("Speck", "Speck", "Meat & Seafood"),
    ("Italian Sausage", "Italian Sausage", "Meat & Seafood"),
    ("Hot Italian Sausage", "Italian Sausage", "Meat & Seafood"),
    ("Sweet Italian Sausage", "Italian Sausage", "Meat & Seafood"),
    ("Chorizo", "Chorizo", "Meat & Seafood"),
    ("Mexican Chorizo", "Chorizo", "Meat & Seafood"),
    ("Spanish Chorizo", "Spanish Chorizo", "Meat & Seafood"),
    ("Andouille Sausage", "Andouille", "Meat & Seafood"),
    ("Kielbasa", "Kielbasa", "Meat & Seafood"),
    ("Bratwurst", "Bratwurst", "Meat & Seafood"),
    ("Merguez Sausage", "Merguez", "Meat & Seafood"),
    ("Breakfast Sausage", "Breakfast Sausage", "Meat & Seafood"),
    ("Breakfast Sausage Links", "Breakfast Sausage", "Meat & Seafood"),
    ("Breakfast Sausage Patties", "Breakfast Sausage", "Meat & Seafood"),
    ("Hot Dogs", "Hot Dogs", "Meat & Seafood"),
    ("Pepperoni", "Pepperoni", "Meat & Seafood"),
    ("Salami", "Salami", "Meat & Seafood"),
    ("Genoa Salami", "Salami", "Meat & Seafood"),
    ("Mortadella", "Mortadella", "Meat & Seafood"),
    ("Lamb Chops", "Lamb Chops", "Meat & Seafood"),
    ("Rack Of Lamb", "Rack Of Lamb", "Meat & Seafood"),
    ("Lamb Shoulder", "Lamb Shoulder", "Meat & Seafood"),
    ("Leg Of Lamb", "Leg Of Lamb", "Meat & Seafood"),
    ("Ground Lamb", "Ground Lamb", "Meat & Seafood"),
    ("Lamb Shank", "Lamb Shank", "Meat & Seafood"),
    ("Lamb Ribs", "Lamb Ribs", "Meat & Seafood"),
    ("Venison", "Venison", "Meat & Seafood"),
    ("Bison", "Bison", "Meat & Seafood"),
    ("Ground Bison", "Bison", "Meat & Seafood"),
    ("Chicken Liver", "Chicken Liver", "Meat & Seafood"),
    ("Beef Liver", "Beef Liver", "Meat & Seafood"),
    ("Chicken Sausage", "Chicken Sausage", "Meat & Seafood"),

    # ─── SEAFOOD ─────────────────────────────────────────────────────
    ("Salmon", "Salmon", "Meat & Seafood"),
    ("Salmon Fillet", "Salmon", "Meat & Seafood"),
    ("Atlantic Salmon", "Salmon", "Meat & Seafood"),
    ("Sockeye Salmon", "Salmon", "Meat & Seafood"),
    ("King Salmon", "Salmon", "Meat & Seafood"),
    ("Coho Salmon", "Salmon", "Meat & Seafood"),
    ("Smoked Salmon", "Smoked Salmon", "Meat & Seafood"),
    ("Lox", "Smoked Salmon", "Meat & Seafood"),
    ("Tuna", "Tuna", "Meat & Seafood"),
    ("Tuna Steak", "Tuna", "Meat & Seafood"),
    ("Ahi Tuna", "Tuna", "Meat & Seafood"),
    ("Yellowfin Tuna", "Tuna", "Meat & Seafood"),
    ("Canned Tuna", "Canned Tuna", "Pantry & Dry Goods"),
    ("Tuna In Water", "Canned Tuna", "Pantry & Dry Goods"),
    ("Cod", "Cod", "Meat & Seafood"),
    ("Cod Fillet", "Cod", "Meat & Seafood"),
    ("Pacific Cod", "Cod", "Meat & Seafood"),
    ("Halibut", "Halibut", "Meat & Seafood"),
    ("Halibut Fillet", "Halibut", "Meat & Seafood"),
    ("Tilapia", "Tilapia", "Meat & Seafood"),
    ("Tilapia Fillet", "Tilapia", "Meat & Seafood"),
    ("Mahi Mahi", "Mahi Mahi", "Meat & Seafood"),
    ("Mahi Mahi Fillet", "Mahi Mahi", "Meat & Seafood"),
    ("Sea Bass", "Sea Bass", "Meat & Seafood"),
    ("Chilean Sea Bass", "Sea Bass", "Meat & Seafood"),
    ("Striped Bass", "Striped Bass", "Meat & Seafood"),
    ("Branzino", "Branzino", "Meat & Seafood"),
    ("Snapper", "Snapper", "Meat & Seafood"),
    ("Red Snapper", "Snapper", "Meat & Seafood"),
    ("Flounder", "Flounder", "Meat & Seafood"),
    ("Sole", "Sole", "Meat & Seafood"),
    ("Dover Sole", "Sole", "Meat & Seafood"),
    ("Trout", "Trout", "Meat & Seafood"),
    ("Rainbow Trout", "Trout", "Meat & Seafood"),
    ("Catfish", "Catfish", "Meat & Seafood"),
    ("Mackerel", "Mackerel", "Meat & Seafood"),
    ("Sardines", "Sardines", "Meat & Seafood"),
    ("Canned Sardines", "Sardines", "Pantry & Dry Goods"),
    ("Anchovies", "Anchovies", "Pantry & Dry Goods"),
    ("Canned Anchovies", "Anchovies", "Pantry & Dry Goods"),
    ("Swordfish", "Swordfish", "Meat & Seafood"),
    ("Swordfish Steak", "Swordfish", "Meat & Seafood"),
    ("Shrimp", "Shrimp", "Meat & Seafood"),
    ("Large Shrimp", "Shrimp", "Meat & Seafood"),
    ("Jumbo Shrimp", "Shrimp", "Meat & Seafood"),
    ("Extra Large Shrimp", "Shrimp", "Meat & Seafood"),
    ("Peeled Shrimp", "Shrimp", "Meat & Seafood"),
    ("Tail-On Shrimp", "Shrimp", "Meat & Seafood"),
    ("Tiger Shrimp", "Shrimp", "Meat & Seafood"),
    ("Gulf Shrimp", "Shrimp", "Meat & Seafood"),
    ("Scallops", "Scallops", "Meat & Seafood"),
    ("Sea Scallops", "Scallops", "Meat & Seafood"),
    ("Bay Scallops", "Bay Scallops", "Meat & Seafood"),
    ("Lobster", "Lobster", "Meat & Seafood"),
    ("Lobster Tail", "Lobster Tail", "Meat & Seafood"),
    ("Lobster Meat", "Lobster", "Meat & Seafood"),
    ("Crab", "Crab", "Meat & Seafood"),
    ("Dungeness Crab", "Crab", "Meat & Seafood"),
    ("King Crab", "King Crab Legs", "Meat & Seafood"),
    ("King Crab Legs", "King Crab Legs", "Meat & Seafood"),
    ("Snow Crab Legs", "Snow Crab Legs", "Meat & Seafood"),
    ("Crab Meat", "Crab Meat", "Meat & Seafood"),
    ("Lump Crab Meat", "Crab Meat", "Meat & Seafood"),
    ("Clams", "Clams", "Meat & Seafood"),
    ("Little Neck Clams", "Clams", "Meat & Seafood"),
    ("Cherrystone Clams", "Clams", "Meat & Seafood"),
    ("Canned Clams", "Canned Clams", "Pantry & Dry Goods"),
    ("Mussels", "Mussels", "Meat & Seafood"),
    ("Oysters", "Oysters", "Meat & Seafood"),
    ("Raw Oysters", "Oysters", "Meat & Seafood"),
    ("Squid", "Squid", "Meat & Seafood"),
    ("Calamari", "Squid", "Meat & Seafood"),
    ("Octopus", "Octopus", "Meat & Seafood"),

    # ─── BROTHS & STOCKS ─────────────────────────────────────────────
    ("Chicken Broth", "Chicken Broth", "Pantry & Dry Goods"),
    ("Chicken Stock", "Chicken Broth", "Pantry & Dry Goods"),
    ("Low Sodium Chicken Broth", "Chicken Broth", "Pantry & Dry Goods"),
    ("Beef Broth", "Beef Broth", "Pantry & Dry Goods"),
    ("Beef Stock", "Beef Broth", "Pantry & Dry Goods"),
    ("Vegetable Broth", "Vegetable Broth", "Pantry & Dry Goods"),
    ("Vegetable Stock", "Vegetable Broth", "Pantry & Dry Goods"),
    ("Fish Stock", "Fish Stock", "Pantry & Dry Goods"),
    ("Seafood Stock", "Fish Stock", "Pantry & Dry Goods"),
    ("Clam Juice", "Clam Juice", "Pantry & Dry Goods"),
    ("Dashi", "Dashi", "Pantry & Dry Goods"),
    ("Bone Broth", "Bone Broth", "Pantry & Dry Goods"),
    ("Beef Bone Broth", "Bone Broth", "Pantry & Dry Goods"),

    # ─── CANNED & JARRED GOODS ───────────────────────────────────────
    ("Canned Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Crushed Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Diced Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Whole Peeled Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("San Marzano Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Fire Roasted Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Stewed Tomatoes", "Canned Tomatoes", "Pantry & Dry Goods"),
    ("Coconut Milk", "Coconut Milk", "Pantry & Dry Goods"),
    ("Full Fat Coconut Milk", "Coconut Milk", "Pantry & Dry Goods"),
    ("Light Coconut Milk", "Coconut Milk", "Pantry & Dry Goods"),
    ("Coconut Cream", "Coconut Cream", "Pantry & Dry Goods"),
    ("Canned Chickpeas", "Chickpeas", "Pantry & Dry Goods"),
    ("Chickpeas", "Chickpeas", "Pantry & Dry Goods"),
    ("Garbanzo Beans", "Chickpeas", "Pantry & Dry Goods"),
    ("Canned Black Beans", "Black Beans", "Pantry & Dry Goods"),
    ("Black Beans", "Black Beans", "Pantry & Dry Goods"),
    ("Canned Kidney Beans", "Kidney Beans", "Pantry & Dry Goods"),
    ("Kidney Beans", "Kidney Beans", "Pantry & Dry Goods"),
    ("Canned Cannellini Beans", "Cannellini Beans", "Pantry & Dry Goods"),
    ("Cannellini Beans", "Cannellini Beans", "Pantry & Dry Goods"),
    ("White Beans", "Cannellini Beans", "Pantry & Dry Goods"),
    ("Canned Pinto Beans", "Pinto Beans", "Pantry & Dry Goods"),
    ("Pinto Beans", "Pinto Beans", "Pantry & Dry Goods"),
    ("Canned Great Northern Beans", "Great Northern Beans", "Pantry & Dry Goods"),
    ("Great Northern Beans", "Great Northern Beans", "Pantry & Dry Goods"),
    ("Canned Navy Beans", "Navy Beans", "Pantry & Dry Goods"),
    ("Navy Beans", "Navy Beans", "Pantry & Dry Goods"),
    ("Canned Lentils", "Lentils", "Pantry & Dry Goods"),
    ("Lentils", "Lentils", "Pantry & Dry Goods"),
    ("Red Lentils", "Red Lentils", "Pantry & Dry Goods"),
    ("Green Lentils", "Lentils", "Pantry & Dry Goods"),
    ("French Lentils", "Lentils", "Pantry & Dry Goods"),
    ("Canned Corn", "Corn", "Pantry & Dry Goods"),
    ("Canned Green Beans", "Green Beans", "Pantry & Dry Goods"),
    ("Canned Peas", "Peas", "Pantry & Dry Goods"),
    ("Roasted Red Peppers", "Roasted Red Peppers", "Pantry & Dry Goods"),
    ("Capers", "Capers", "Spices & Condiments"),
    ("Olives", "Olives", "Pantry & Dry Goods"),
    ("Kalamata Olives", "Kalamata Olives", "Pantry & Dry Goods"),
    ("Green Olives", "Olives", "Pantry & Dry Goods"),
    ("Black Olives", "Olives", "Pantry & Dry Goods"),
    ("Canned Pumpkin", "Pumpkin Puree", "Pantry & Dry Goods"),
    ("Pumpkin Puree", "Pumpkin Puree", "Pantry & Dry Goods"),

    # ─── PASTA ───────────────────────────────────────────────────────
    ("Spaghetti", "Spaghetti", "Pantry & Dry Goods"),
    ("Linguine", "Linguine", "Pantry & Dry Goods"),
    ("Fettuccine", "Fettuccine", "Pantry & Dry Goods"),
    ("Tagliatelle", "Tagliatelle", "Pantry & Dry Goods"),
    ("Pappardelle", "Pappardelle", "Pantry & Dry Goods"),
    ("Bucatini", "Bucatini", "Pantry & Dry Goods"),
    ("Penne", "Penne", "Pantry & Dry Goods"),
    ("Rigatoni", "Rigatoni", "Pantry & Dry Goods"),
    ("Ziti", "Ziti", "Pantry & Dry Goods"),
    ("Fusilli", "Fusilli", "Pantry & Dry Goods"),
    ("Rotini", "Rotini", "Pantry & Dry Goods"),
    ("Farfalle", "Farfalle", "Pantry & Dry Goods"),
    ("Orecchiette", "Orecchiette", "Pantry & Dry Goods"),
    ("Cavatappi", "Cavatappi", "Pantry & Dry Goods"),
    ("Gemelli", "Gemelli", "Pantry & Dry Goods"),
    ("Shells", "Shells", "Pantry & Dry Goods"),
    ("Elbow Macaroni", "Elbow Macaroni", "Pantry & Dry Goods"),
    ("Ditalini", "Ditalini", "Pantry & Dry Goods"),
    ("Orzo", "Orzo", "Pantry & Dry Goods"),
    ("Lasagna Noodles", "Lasagna Noodles", "Pantry & Dry Goods"),
    ("Lasagna Sheets", "Lasagna Noodles", "Pantry & Dry Goods"),
    ("Egg Noodles", "Egg Noodles", "Pantry & Dry Goods"),
    ("Fresh Pasta", "Fresh Pasta", "Pantry & Dry Goods"),
    ("Gnocchi", "Gnocchi", "Pantry & Dry Goods"),
    ("Rice Noodles", "Rice Noodles", "Pantry & Dry Goods"),
    ("Rice Vermicelli", "Rice Noodles", "Pantry & Dry Goods"),
    ("Udon Noodles", "Udon Noodles", "Pantry & Dry Goods"),
    ("Soba Noodles", "Soba Noodles", "Pantry & Dry Goods"),
    ("Ramen Noodles", "Ramen Noodles", "Pantry & Dry Goods"),
    ("Lo Mein Noodles", "Lo Mein Noodles", "Pantry & Dry Goods"),
    ("Glass Noodles", "Glass Noodles", "Pantry & Dry Goods"),
    ("Cellophane Noodles", "Glass Noodles", "Pantry & Dry Goods"),
    ("Couscous", "Couscous", "Pantry & Dry Goods"),
    ("Israeli Couscous", "Israeli Couscous", "Pantry & Dry Goods"),
    ("Pearl Couscous", "Israeli Couscous", "Pantry & Dry Goods"),

    # ─── GRAINS & RICE ───────────────────────────────────────────────
    ("White Rice", "Rice", "Pantry & Dry Goods"),
    ("Long Grain White Rice", "Rice", "Pantry & Dry Goods"),
    ("Brown Rice", "Brown Rice", "Pantry & Dry Goods"),
    ("Basmati Rice", "Basmati Rice", "Pantry & Dry Goods"),
    ("Jasmine Rice", "Jasmine Rice", "Pantry & Dry Goods"),
    ("Arborio Rice", "Arborio Rice", "Pantry & Dry Goods"),
    ("Carnaroli Rice", "Arborio Rice", "Pantry & Dry Goods"),
    ("Sushi Rice", "Sushi Rice", "Pantry & Dry Goods"),
    ("Short Grain Rice", "Sushi Rice", "Pantry & Dry Goods"),
    ("Wild Rice", "Wild Rice", "Pantry & Dry Goods"),
    ("Black Rice", "Black Rice", "Pantry & Dry Goods"),
    ("Red Rice", "Red Rice", "Pantry & Dry Goods"),
    ("Quinoa", "Quinoa", "Pantry & Dry Goods"),
    ("Red Quinoa", "Quinoa", "Pantry & Dry Goods"),
    ("Tri-Color Quinoa", "Quinoa", "Pantry & Dry Goods"),
    ("Farro", "Farro", "Pantry & Dry Goods"),
    ("Barley", "Barley", "Pantry & Dry Goods"),
    ("Pearl Barley", "Barley", "Pantry & Dry Goods"),
    ("Bulgur", "Bulgur", "Pantry & Dry Goods"),
    ("Bulgur Wheat", "Bulgur", "Pantry & Dry Goods"),
    ("Freekeh", "Freekeh", "Pantry & Dry Goods"),
    ("Millet", "Millet", "Pantry & Dry Goods"),
    ("Oats", "Oats", "Pantry & Dry Goods"),
    ("Rolled Oats", "Oats", "Pantry & Dry Goods"),
    ("Old Fashioned Oats", "Oats", "Pantry & Dry Goods"),
    ("Quick Oats", "Oats", "Pantry & Dry Goods"),
    ("Steel Cut Oats", "Steel Cut Oats", "Pantry & Dry Goods"),
    ("Oat Groats", "Steel Cut Oats", "Pantry & Dry Goods"),
    ("Wheat Berries", "Wheat Berries", "Pantry & Dry Goods"),
    ("Amaranth", "Amaranth", "Pantry & Dry Goods"),
    ("Teff", "Teff", "Pantry & Dry Goods"),
    ("Buckwheat", "Buckwheat", "Pantry & Dry Goods"),
    ("Buckwheat Groats", "Buckwheat", "Pantry & Dry Goods"),
    ("Kasha", "Buckwheat", "Pantry & Dry Goods"),
    ("Spelt", "Spelt", "Pantry & Dry Goods"),
    ("Kamut", "Kamut", "Pantry & Dry Goods"),

    # ─── NUTS & SEEDS ────────────────────────────────────────────────
    ("Almonds", "Almonds", "Pantry & Dry Goods"),
    ("Sliced Almonds", "Almonds", "Pantry & Dry Goods"),
    ("Slivered Almonds", "Almonds", "Pantry & Dry Goods"),
    ("Blanched Almonds", "Almonds", "Pantry & Dry Goods"),
    ("Walnuts", "Walnuts", "Pantry & Dry Goods"),
    ("Walnut Halves", "Walnuts", "Pantry & Dry Goods"),
    ("Pecans", "Pecans", "Pantry & Dry Goods"),
    ("Pecan Halves", "Pecans", "Pantry & Dry Goods"),
    ("Cashews", "Cashews", "Pantry & Dry Goods"),
    ("Raw Cashews", "Cashews", "Pantry & Dry Goods"),
    ("Pistachios", "Pistachios", "Pantry & Dry Goods"),
    ("Shelled Pistachios", "Pistachios", "Pantry & Dry Goods"),
    ("Pine Nuts", "Pine Nuts", "Pantry & Dry Goods"),
    ("Hazelnuts", "Hazelnuts", "Pantry & Dry Goods"),
    ("Macadamia Nuts", "Macadamia Nuts", "Pantry & Dry Goods"),
    ("Brazil Nuts", "Brazil Nuts", "Pantry & Dry Goods"),
    ("Peanuts", "Peanuts", "Pantry & Dry Goods"),
    ("Dry Roasted Peanuts", "Peanuts", "Pantry & Dry Goods"),
    ("Peanut Butter", "Peanut Butter", "Pantry & Dry Goods"),
    ("Almond Butter", "Almond Butter", "Pantry & Dry Goods"),
    ("Cashew Butter", "Cashew Butter", "Pantry & Dry Goods"),
    ("Sunflower Seeds", "Sunflower Seeds", "Pantry & Dry Goods"),
    ("Pumpkin Seeds", "Pumpkin Seeds", "Pantry & Dry Goods"),
    ("Pepitas", "Pumpkin Seeds", "Pantry & Dry Goods"),
    ("Flaxseeds", "Flaxseeds", "Pantry & Dry Goods"),
    ("Ground Flaxseed", "Flaxseeds", "Pantry & Dry Goods"),
    ("Chia Seeds", "Chia Seeds", "Pantry & Dry Goods"),
    ("Hemp Seeds", "Hemp Seeds", "Pantry & Dry Goods"),
    ("Coconut Flakes", "Coconut Flakes", "Pantry & Dry Goods"),
    ("Shredded Coconut", "Coconut Flakes", "Pantry & Dry Goods"),
    ("Desiccated Coconut", "Coconut Flakes", "Pantry & Dry Goods"),

    # ─── WINES, SPIRITS & COOKING LIQUIDS ───────────────────────────
    ("White Wine", "White Wine", "Pantry & Dry Goods"),
    ("Dry White Wine", "White Wine", "Pantry & Dry Goods"),
    ("Red Wine", "Red Wine", "Pantry & Dry Goods"),
    ("Dry Red Wine", "Red Wine", "Pantry & Dry Goods"),
    ("Sparkling Wine", "Sparkling Wine", "Pantry & Dry Goods"),
    ("Champagne", "Sparkling Wine", "Pantry & Dry Goods"),
    ("Rosé Wine", "Rosé Wine", "Pantry & Dry Goods"),
    ("Port Wine", "Port Wine", "Pantry & Dry Goods"),
    ("Marsala Wine", "Marsala Wine", "Pantry & Dry Goods"),
    ("Sherry", "Sherry", "Pantry & Dry Goods"),
    ("Dry Sherry", "Sherry", "Pantry & Dry Goods"),
    ("Vermouth", "Vermouth", "Pantry & Dry Goods"),
    ("Dry Vermouth", "Vermouth", "Pantry & Dry Goods"),
    ("Beer", "Beer", "Pantry & Dry Goods"),
    ("Lager", "Beer", "Pantry & Dry Goods"),
    ("Ale", "Beer", "Pantry & Dry Goods"),
    ("Stout", "Stout", "Pantry & Dry Goods"),
    ("Bourbon", "Bourbon", "Pantry & Dry Goods"),
    ("Whiskey", "Whiskey", "Pantry & Dry Goods"),
    ("Rum", "Rum", "Pantry & Dry Goods"),
    ("Brandy", "Brandy", "Pantry & Dry Goods"),
    ("Cognac", "Cognac", "Pantry & Dry Goods"),
    ("Vodka", "Vodka", "Pantry & Dry Goods"),
    ("Gin", "Gin", "Pantry & Dry Goods"),
    ("Tequila", "Tequila", "Pantry & Dry Goods"),
    ("Kahlua", "Kahlua", "Pantry & Dry Goods"),
    ("Grand Marnier", "Grand Marnier", "Pantry & Dry Goods"),
    ("Amaretto", "Amaretto", "Pantry & Dry Goods"),
    ("Coffee Liqueur", "Coffee Liqueur", "Pantry & Dry Goods"),
    ("Orange Liqueur", "Orange Liqueur", "Pantry & Dry Goods"),

    # ─── BREAD & BAKERY ──────────────────────────────────────────────
    ("Bread", "Bread", "Bread & Bakery"),
    ("White Bread", "Bread", "Bread & Bakery"),
    ("Sourdough Bread", "Sourdough Bread", "Bread & Bakery"),
    ("Whole Wheat Bread", "Whole Wheat Bread", "Bread & Bakery"),
    ("Multigrain Bread", "Multigrain Bread", "Bread & Bakery"),
    ("Rye Bread", "Rye Bread", "Bread & Bakery"),
    ("Pumpernickel Bread", "Pumpernickel", "Bread & Bakery"),
    ("Ciabatta", "Ciabatta", "Bread & Bakery"),
    ("Focaccia", "Focaccia", "Bread & Bakery"),
    ("Baguette", "Baguette", "Bread & Bakery"),
    ("French Bread", "French Bread", "Bread & Bakery"),
    ("Italian Bread", "Italian Bread", "Bread & Bakery"),
    ("Brioche", "Brioche", "Bread & Bakery"),
    ("Challah", "Challah", "Bread & Bakery"),
    ("Pita Bread", "Pita", "Bread & Bakery"),
    ("Pita", "Pita", "Bread & Bakery"),
    ("Naan", "Naan", "Bread & Bakery"),
    ("Flatbread", "Flatbread", "Bread & Bakery"),
    ("Flour Tortillas", "Flour Tortillas", "Bread & Bakery"),
    ("Corn Tortillas", "Corn Tortillas", "Bread & Bakery"),
    ("Tortillas", "Tortillas", "Bread & Bakery"),
    ("Taco Shells", "Taco Shells", "Bread & Bakery"),
    ("Burger Buns", "Burger Buns", "Bread & Bakery"),
    ("Hot Dog Buns", "Hot Dog Buns", "Bread & Bakery"),
    ("English Muffins", "English Muffins", "Bread & Bakery"),
    ("Bagels", "Bagels", "Bread & Bakery"),
    ("Croissants", "Croissants", "Bread & Bakery"),
    ("Crumpets", "Crumpets", "Bread & Bakery"),
    ("Phyllo Dough", "Phyllo Dough", "Bread & Bakery"),
    ("Puff Pastry", "Puff Pastry", "Bread & Bakery"),
    ("Pie Crust", "Pie Crust", "Bread & Bakery"),
    ("Pizza Dough", "Pizza Dough", "Bread & Bakery"),
    ("Wonton Wrappers", "Wonton Wrappers", "Bread & Bakery"),
    ("Dumpling Wrappers", "Dumpling Wrappers", "Bread & Bakery"),
    ("Spring Roll Wrappers", "Spring Roll Wrappers", "Bread & Bakery"),
    ("Rice Paper Wrappers", "Rice Paper Wrappers", "Bread & Bakery"),

    # ─── FROZEN ──────────────────────────────────────────────────────
    ("Frozen Peas", "Peas", "Frozen"),
    ("Frozen Corn", "Corn", "Frozen"),
    ("Frozen Spinach", "Spinach", "Frozen"),
    ("Frozen Broccoli", "Broccoli", "Frozen"),
    ("Frozen Mixed Vegetables", "Mixed Vegetables", "Frozen"),
    ("Frozen Edamame", "Edamame", "Frozen"),
    ("Frozen Green Beans", "Green Beans", "Frozen"),
    ("Frozen Lima Beans", "Lima Beans", "Frozen"),
    ("Frozen Strawberries", "Strawberries", "Frozen"),
    ("Frozen Blueberries", "Blueberries", "Frozen"),
    ("Frozen Raspberries", "Raspberries", "Frozen"),
    ("Frozen Mango", "Mango", "Frozen"),
    ("Frozen Shrimp", "Shrimp", "Frozen"),
    ("Frozen Scallops", "Scallops", "Frozen"),
    ("Frozen Salmon", "Salmon", "Frozen"),
    ("Frozen Fish Fillets", "Fish Fillets", "Frozen"),
    ("Frozen Chicken Breast", "Chicken Breast", "Frozen"),
    ("Frozen Chicken Thighs", "Chicken Thighs", "Frozen"),

    # ─── OTHER PANTRY ────────────────────────────────────────────────
    ("Tofu", "Tofu", "Pantry & Dry Goods"),
    ("Firm Tofu", "Tofu", "Pantry & Dry Goods"),
    ("Silken Tofu", "Silken Tofu", "Pantry & Dry Goods"),
    ("Extra Firm Tofu", "Tofu", "Pantry & Dry Goods"),
    ("Tempeh", "Tempeh", "Pantry & Dry Goods"),
    ("Seitan", "Seitan", "Pantry & Dry Goods"),
    ("Nori", "Nori", "Pantry & Dry Goods"),
    ("Dried Nori Sheets", "Nori", "Pantry & Dry Goods"),
    ("Wakame", "Wakame", "Pantry & Dry Goods"),
    ("Dried Kombu", "Kombu", "Pantry & Dry Goods"),
    ("Sun-Dried Tomatoes In Oil", "Sun-Dried Tomatoes", "Pantry & Dry Goods"),
    ("Dried Lentils", "Lentils", "Pantry & Dry Goods"),
    ("Split Peas", "Split Peas", "Pantry & Dry Goods"),
    ("Yellow Split Peas", "Split Peas", "Pantry & Dry Goods"),
    ("Green Split Peas", "Split Peas", "Pantry & Dry Goods"),
    ("Dried Black Beans", "Black Beans", "Pantry & Dry Goods"),
    ("Dried Chickpeas", "Chickpeas", "Pantry & Dry Goods"),
    ("Dried Kidney Beans", "Kidney Beans", "Pantry & Dry Goods"),
    ("Dried Cannellini Beans", "Cannellini Beans", "Pantry & Dry Goods"),
    ("Dried Pinto Beans", "Pinto Beans", "Pantry & Dry Goods"),
    ("Dried Lima Beans", "Lima Beans", "Pantry & Dry Goods"),
    ("Lima Beans", "Lima Beans", "Pantry & Dry Goods"),
    ("Butter Beans", "Lima Beans", "Pantry & Dry Goods"),
    ("Espresso", "Espresso", "Pantry & Dry Goods"),
    ("Coffee", "Coffee", "Pantry & Dry Goods"),
    ("Instant Coffee", "Instant Coffee", "Pantry & Dry Goods"),
    ("Espresso Powder", "Espresso Powder", "Pantry & Dry Goods"),
    ("Tea", "Tea", "Pantry & Dry Goods"),
    ("Matcha Powder", "Matcha", "Pantry & Dry Goods"),
    ("Coconut Water", "Coconut Water", "Pantry & Dry Goods"),
    ("Vegetable Shortening", "Shortening", "Pantry & Dry Goods"),
    ("Lard", "Lard", "Pantry & Dry Goods"),
    ("Chicken Fat", "Schmaltz", "Pantry & Dry Goods"),
    ("Schmaltz", "Schmaltz", "Pantry & Dry Goods"),
    ("Duck Fat", "Duck Fat", "Pantry & Dry Goods"),
    ("Nutritional Yeast", "Nutritional Yeast", "Pantry & Dry Goods"),
    ("Liquid Smoke", "Liquid Smoke", "Spices & Condiments"),
    ("Worcestershire", "Worcestershire Sauce", "Spices & Condiments"),
    ("Tomato Ketchup", "Ketchup", "Spices & Condiments"),
    ("Pickle Juice", "Pickle Juice", "Spices & Condiments"),
    ("Dill Pickles", "Dill Pickles", "Pantry & Dry Goods"),
    ("Bread And Butter Pickles", "Pickles", "Pantry & Dry Goods"),
    ("Giardiniera", "Giardiniera", "Pantry & Dry Goods"),
    ("Horseradish", "Horseradish", "Spices & Condiments"),
    ("Prepared Horseradish", "Horseradish", "Spices & Condiments"),
    ("Wasabi", "Wasabi", "Spices & Condiments"),
    ("Wasabi Paste", "Wasabi", "Spices & Condiments"),
    ("Sauerkraut", "Sauerkraut", "Pantry & Dry Goods"),
    ("Kimchi", "Kimchi", "Pantry & Dry Goods"),
    ("Preserved Lemons", "Preserved Lemons", "Pantry & Dry Goods"),
    ("Canned Pumpkin Puree", "Pumpkin Puree", "Pantry & Dry Goods"),
    ("Applesauce", "Applesauce", "Pantry & Dry Goods"),
    ("Jam", "Jam", "Pantry & Dry Goods"),
    ("Strawberry Jam", "Jam", "Pantry & Dry Goods"),
    ("Raspberry Jam", "Jam", "Pantry & Dry Goods"),
    ("Apricot Jam", "Jam", "Pantry & Dry Goods"),
    ("Marmalade", "Marmalade", "Pantry & Dry Goods"),
    ("Jelly", "Jelly", "Pantry & Dry Goods"),
    ("Grape Jelly", "Jelly", "Pantry & Dry Goods"),
    ("Nutella", "Nutella", "Pantry & Dry Goods"),
    ("Cream Of Mushroom Soup", "Cream Of Mushroom Soup", "Pantry & Dry Goods"),
    ("Cream Of Chicken Soup", "Cream Of Chicken Soup", "Pantry & Dry Goods"),
]


def main():
    # Deduplicate within the list itself (case-insensitive on name), keeping first occurrence
    seen: set[str] = set()
    unique_rows = []
    for name, canonical_name, grocery_category in INGREDIENTS:
        key = name.lower().strip()
        if key not in seen:
            seen.add(key)
            unique_rows.append({
                "name": name,
                "canonical_name": canonical_name,
                "grocery_category": grocery_category,
                "aliases": "",
            })

    df = pd.DataFrame(unique_rows, columns=["name", "canonical_name", "grocery_category", "aliases"])

    out_path = DATA_DIR / "ingredient_lookup.csv"
    df.to_csv(out_path, index=False)

    print(f"Total rows written: {len(df)}")
    print()
    print("Count per grocery_category:")
    for cat, count in df["grocery_category"].value_counts().items():
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
